### ISSUE TITLE
There are a couple of bugs in the code.

### ISSUE THREAD

**Issue by ShelleyDong** [filipecalasans/ringbuffer#1]
You forgot to move the pointer correctly before memory copy in the following functions.

void ringBufferAppendMultiple(RingBuffer *buffer, uint8_t *data, uint32_t len){
   if(buffer->tail + len > buffer->sizeMask) {
      uint32_t lenToTheEnd = buffer->sizeMask - buffer->tail + 1;
      uint32_t lenFromBegin = len - lenToTheEnd;
      memcpy(buffer->data + buffer->tail, data, lenToTheEnd);
      memcpy(buffer->data, data + lenToTheEnd, lenFromBegin);
   }
   else {
      **memcpy(buffer->data + buffer->tail, data, len);**
   }
   buffer->tail = (buffer->tail + len) & buffer->sizeMask;
}

void ringBufferPeekMultiple(RingBuffer *buffer, uint8_t *dst, uint32_t len){
   if(buffer->head + len > buffer->sizeMask) {
      uint32_t lenToTheEnd = buffer->sizeMask - buffer->head + 1;
      uint32_t lenFromBegin = len - lenToTheEnd;
      memcpy(dst, buffer->data + buffer->head, lenToTheEnd);
      memcpy(dst + lenToTheEnd, buffer->data, lenFromBegin);
   }
   else {
      **memcpy(dst, buffer->data + buffer->head, len);**
   }
}

**Comment by filipecalasans** [comment]
Thanks for spotting the bugs. Would you like to put a pull request fixing? I would gladly accept it!

**Comment by filipecalasans** [comment]
Issue fixed on master in https://github.com/filipecalasans/ringbuffer/commit/75a1d21edeeb33054ab82882b7fa0dc4d2dd2d52
